# Generated by Django 4.2.7 on 2023-11-07 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('age', models.DateField()),
                ('registeredDate', models.DateField(auto_now_add=True)),
                ('role', models.CharField(choices=[('ATENDENTE', 'Atendente'), ('CAIXA', 'Caixa'), ('REPOSITOR', 'Repositor'), ('GERENTE', 'Gerente'), ('DEFININDO', 'Definindo')], default='DEFININDO', max_length=20)),
            ],
        ),
    ]
