# Generated by Django 4.2.7 on 2023-11-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0002_marketroles_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketRoles',
            new_name='MarketRole',
        ),
    ]
