# Generated by Django 4.2.7 on 2023-11-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0005_alter_marketrole_accessibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketrole',
            name='accessibility',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
