# Generated by Django 4.2.7 on 2023-11-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountManagement', '0006_alter_marketrole_accessibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='born',
        ),
    ]
